### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by qingxiali** [unmannedlab/imu_lidar_calibration#1]
hello,I get an error when I run the program,Segmentation fault (core dumped).I pinpointed the cause of the error,in file ros_calib_init.cpp"    LOdom = std::make_shared<lin_core::LidarOdometry>(ndt_resolution, "", true);".Do you know what caused it?Looking forward to your reply.

**Comment by SubMishMar** [comment]
Yes. I have seen this issue in a few systems. I have dockerized the code for cross platform usage. Please try to use the docker image.

**Comment by Doodle1106** [comment]
I think it might by related to NDT-omp: https://github.com/koide3/ndt_omp/issues/6

**Comment by Cracks-ll** [comment]
@SubMishMar @qingxiali @Doodle1106 What is the message type of lidar? velodyne_scan or pointcloud2?
