### ISSUE TITLE
did it work betwwen external imu and lidar?

### ISSUE THREAD

**Issue by Wuxinxiaoshifu** [unmannedlab/imu_lidar_calibration#3]
i just want to make sure that does it work between external imu and lidar, which get transform between lidar and external imu?or it only get the transform between ouster's internal imu and lidar?

**Comment by SubMishMar** [comment]
Yes. The repository was used to calibrate a setup described in this paper https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9591180

**Comment by Wuxinxiaoshifu** [comment]
> Yes. The repository was used to calibrate a setup described in this paper https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9591180

thanks
